version: '4.14.1'
services:
  db:
    image: postgres:16.2-alpine
    container_name: vitasoft-test-postgres
    ports:
      - "127.0.0.1:6432:5432"
    environment:
      - POSTGRES_DB=vitasoft-test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5